version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    networks:
      - app-network

  node:
    build:
      context: ./node-app
      dockerfile: ../Dockerfile
    container_name: node
    image: node:16-alpine
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s
    volumes:
      - ./node-app:/usr/src/app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=app_db
    ports:
      - "3000:3000"
    command: sh -c "npm install && node server.js"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
